chore: rename to megagraph
Opty-Fi/megagraph pull request #27
Opened 2021-11-02 22:31 UTC by uwe

This repository was renamed from `defi-protocol-subgraph` to `megagraph`. This PR removes all references to the old name.

The links in the README become valid once it is deployed with its new name.

2021-11-05 19:54 UTC, dhruvinparikh requested changes

2021-11-05 19:54 UTC, dhruvinparikh commented on README.md
> +* Subscription : wss://api.thegraph.com/subgraphs/name/opty-fi/megagraph
This cannot be changed right now. It requires a fresh subgraph deployment.

2021-11-08 15:12 UTC, dhruvinparikh approved these changes

2021-11-08 16:05 UTC, undermethod approved these changes
Lookin' good!

2021-11-08 19:01 UTC, merged