fix: ignore user_weight in VoteForGaugeEvent
Opty-Fi/megagraph pull request #28
Opened 2021-11-06 20:33 UTC by uwe

Like stated in Discourse the `gaugeWeight` in `CurveGaugeData` was always way too low.

Turns out we have to ignore the `user_weight` in `VoteForGaugeEvent`, so that the correct weight is pulled from the blockchain.

2021-11-15 19:44 UTC, undermethod requested changes
I think it should be removed instead of commented out.

2021-11-15 19:44 UTC, undermethod commented on src/Curve/mappings/GaugeController.ts
> +    // event.params.weight is the user_weight for this vote -> ignore it
```suggestion
```
I think the note of ignoring `weight` (gaugeWeight) can be in the commit message rather than an inline comment.

2021-11-16 20:55 UTC, undermethod approved these changes
Lookin' good, thanks @uwe! Over to you @dhruvinparikh, let's please keep the reason for ignoring gaugeWeight in the squash & merge msg.

2021-11-16 20:59 UTC, leodinh approved these changes

2021-11-17 03:16 UTC, dhruvinparikh approved these changes

2021-11-17 03:16 UTC, merged